### ISSUE TITLE
Missing def_sort.py

### ISSUE THREAD

**Issue by JingmingR** [Chunfang/defmod-swpc#2]
Hi,

For sorting the result from the F2Dp example, a python file def_sort.py was used in the example. But there are only `fd_sort.py` & `fe_sort.py` in the `/src/tool/` and they can't read the output file.  I tried to use the `fe_sort.py` but seems like it is not compatible and having the below error:
```
Merge observation grid/data...
Merge seismic fault slip grid/data...
fault patch 687/687 merged
Merge pseudo time fault grid/data...
Traceback (most recent call last):
  File "../../../src/tool/fe_sort.py", line 200, in <module>
    fcoord=np.vstack((fcoord,np.genfromtxt(islice(f,n),delimiter=" ",unpack=False,dtype=np.float)))
  File "/Users/jingmingruan/miniconda3/envs/py2p7/lib/python2.7/site-packages/numpy/lib/npyio.py", line 2075, in genfromtxt
    raise ValueError(errmsg)
ValueError: Some errors were detected !
    Line #2 (got 5 columns instead of 1)
    Line #4 (got 2 columns instead of 1)
    Line #10 (got 3 columns instead of 1)
    Line #13 (got 2 columns instead of 1)
...........
```
Would you mind having a look at it? Thank you in advance.

Jim

**Comment by Chunfang** [comment]
I moved all slip data to h5 format, but the postprocessing script for
rate-and-state friction problem was not updated. Other examples should work
fine.

**Comment by JingmingR** [comment]
Hi,

I used both PFLOTRAN and Defmod to model the F3Db and F3Db_usg examples, and found that the results are always missing the No.4 receiver as all the `*ofe*.h5` files only contain output from receiver [1 2 3 5 6]. 

And I assume the missing one is [-1.5, 0., -3.] from  `F3D_bd_usg.py`.
```
ogrid = np.array([[-0.0, 0., -3.],
                  [-0.5, 0., -3.],
                  [-1.0, 0., -3.],
                  [-1.5, 0., -3.],
                  [-2.0, 0., -3.],
                  [-2.5, 0., -3.]])
```

Thank you.
