### ISSUE TITLE
inf and nan in both vector uu and output files

### ISSUE THREAD

**Issue by JingmingR** [Chunfang/defmod-swpc#4]
I made several 2D poroelastic faulting problems based on the example P2D and Fb3D_usg,  the resulting vtk output or h5 output all `nan` and `inf`, and that always happen after step 1. I made sure the coordinates were defined in km and inp parameters are similar to the F2dp example. 

I also checked with the debug mode and found both `inf` and  `nan` were collected from the vector `uu`. 

`t_lim` was set with relatively low value and the fault couldn't be stabilized for 1 dynamic run. Would that also affect the rest of the static run? But if that is the case, the dynamic runs in example `F3Db` are also not stabilized and the output are still fine.

**Comment by Chunfang** [comment]
Usually it is due to dynamic time step being too large. Does the dynamic
run, given enough time, converge at all?
Check out the latest paper https://doi.org/10.1785/0220190234

**Comment by JingmingR** [comment]
dt_dyn is set enough small value and the dynamic run converged as well, for the first several dynamic time step,  the displacement is extremely large up to 1e+154, then nan values occur in the following dynamic run. As the same result from the example F2Dp.

**Comment by JingmingR** [comment]
Though the dynamic timestep is low as 1.6e-06, the displacement filed increased significantly in the top and bottom boundaries of the reservoir (the location of NCF interface), and very little displacement happen in the fault nodes. when the displacement value reach 1e+154, the output become full of nan and inf. 

Parameter setting is similar to F3Db and I assmue they are good and wont cause this exponential increase of the displacement. I will try a new one without NCF interface.

![image](https://user-images.githubusercontent.com/48844980/74853937-e4cded00-533e-11ea-81cc-1c776ee2656c.png)

**Comment by Chunfang** [comment]
NCF is to constrain hanging nodes, there should be no slip at all. I will
check the 2D problem.

**Comment by JingmingR** [comment]
This example without NCF is working fine, the problem might related to NCF constraint in the F2Dp.

![image](https://user-images.githubusercontent.com/48844980/74962600-87a26c00-5410-11ea-9e49-3ba4b8eda89a.png)

**Comment by JingmingR** [comment]
I think the results are highly sensitive to the shape of the elements, I use Gmsh to make transfinite mesh with denser meshes near the fault (using progression), they all failed with the same errors from F2Dp.

![image](https://user-images.githubusercontent.com/48844980/75163658-e4a76600-571f-11ea-863b-44591ff409fe.png)

It went well when I dont use progression, like this:

![image](https://user-images.githubusercontent.com/48844980/75163922-4d8ede00-5720-11ea-8c79-2016925f1986.png)

**Comment by Chunfang** [comment]
Try triangular cells, and see if any changes.

**Comment by JingmingR** [comment]
Using triangular mesh is similar to regular shape quadrature (I think it is better), without data explosion. 

![image](https://user-images.githubusercontent.com/48844980/75275414-c7989300-5804-11ea-9370-838535d3bcf0.png)

Another question is that I tried a lot of traction setting, but most of them are aseismic faulting, could you explain the criterion of that? Thank you!

**Comment by Chunfang** [comment]
It looks fine, is it poroelastic model? A straight fault will slip as
whole, when differential stress is large enough. If you define as spot with
less maximum friction, you may see rupture propagation.

**Comment by JingmingR** [comment]
Yes It is a poroelastic model, and I have several questions on how the Defmod handle hydrostatic pressure:
1. In example like SCEC2D-10 and other models without poroelastic problems, I see there are only tractions on the boundaries defnined, so will Defmod automatically calculate the vertical & horizontal stress with the defined density?
2. In example like F3Db and F2Dp, I am not sure the liquid pressure from PFLOTRAN output is used  as pore pressure or hydrostatic pressure by the Defmod. If it is hydrostatic pressure, I don't know how Defmod calculate stress field in a poroelastic problem.
Thank you in advance!

**Comment by Chunfang** [comment]
On Fri, Feb 28, 2020 at 7:17 AM Jingming Ruan <notifications@github.com>
wrote:

> Yes It is a poroelastic model, and I have several questions on how the
> Defmod handle hydrostatic pressure:
>
>    1. In example like SCEC2D-10 and other models without poroelastic
>    problems, I see there are only tractions on the boundaries defnined, so
>    will Defmod automatically calculate the vertical & horizontal stress with
>    the defined density?
>
> See the instruction on how to turn on the body force (bod_frc). In 2D the
force is in -y.


>
>    1. In example like F3Db and F2Dp, I am not sure the liquid pressure
>    from PFLOTRAN output is used as pore pressure or hydrostatic pressure by
>    the Defmod. If it is hydrostatic pressure, I don't know how Defmod
>    calculate stress field in a poroelastic problem.
>    Thank you in advance!
>
> PFLOTRAN has hydrostatic pressure due to fluid body force, but Defmod does
not. I imposed whole domain pressure from PFLOTRAN once as initial
condition, and later only calculate pressure changes. The initial pressure
gradient is subtracted, because there is no fluid body force to balance it.
I am working the code to have initial pressure all by Defmod.

I have a question. Is there anybody using the cubic triaxial machine
downstairs, and who is leading the rock mechanics researches?
