### ISSUE TITLE
Additional PETSc configure option from 3.16

### ISSUE THREAD

**Issue by JingmingR** [Chunfang/defmod-swpc#5]
Dear Chunfang,

Since PETSc 3.16, for configure with `--download-hdf5`, fortran module files are not included anymore. This results in the missing "hdf5.mod" error when comping Defmod. It needs extra option with `--download-hdf5-fortran-bindings`. Thanks!
[https://petsc.org/main/docs/changes/316/](url)

Greetings,
Jingming

**Comment by Chunfang** [comment]
Thanks!
